import { test, expect } from '@playwright/test';

const adminPassword=process.env.PRINTERWLAN_ADMIN_PASSWORD||'';
const originalUserPassword=process.env.PRINTERWLAN_TEST_USER_PASSWORD||'';
let userPassword=originalUserPassword;

async function adminLogin(page){await page.goto('/');await page.getByRole('button',{name:'管理员登录'}).click();await page.getByLabel('管理员密码').fill(adminPassword);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByText('使用记录',{exact:true}).first()).toBeVisible()}
async function userLogin(page){await page.goto('/');await page.getByLabel('用户名').fill('测试用户');await page.getByLabel('密码').fill(userPassword);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:'打印文件'})).toBeVisible()}

test.describe.serial('PrinterWLAN UI',()=>{
  test('real LAN HTTP boots without secure-context randomUUID',async({page,request})=>{const pageErrors=[];const consoleErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});await page.setViewportSize({width:390,height:844});await page.goto('/');const environment=await page.evaluate(()=>({protocol:location.protocol,hostname:location.hostname,secure:globalThis.isSecureContext,randomUuid:typeof globalThis.crypto?.randomUUID}));expect(environment.protocol).toBe('http:');if(process.env.PRINTERWLAN_REQUIRE_LAN_HTTP==='1'){expect(environment.hostname).not.toMatch(/^(localhost|127\.|\[?::1\]?$)/);expect(environment.secure).toBe(false);expect(environment.randomUuid).toBe('undefined')}await expect(page.getByRole('button',{name:'管理员登录'})).toBeVisible();await page.getByRole('button',{name:'管理员登录'}).click();await expect(page.getByRole('heading',{name:'管理员登录'})).toBeVisible();await page.getByRole('button',{name:'返回用户登录'}).click();await page.getByLabel('用户名').fill('测试用户');await page.getByLabel('密码').fill(originalUserPassword);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('heading',{name:'打印文件'})).toBeVisible();expect(pageErrors.filter(message=>message.includes('randomUUID'))).toEqual([]);expect(consoleErrors.filter(message=>message.includes('randomUUID'))).toEqual([]);expect((await request.get('/favicon.svg')).status()).toBe(200)});

  for(const width of [320,360,390,768,1366,1920])test(`login layout ${width}px`,async({page})=>{await page.setViewportSize({width,height:width<500?800:900});await page.goto('/');await expect(page.getByRole('button',{name:'管理员登录'})).toBeVisible();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);expect(overflow).toBeLessThanOrEqual(1);const buttons=await page.locator('button').all();for(const button of buttons){const box=await button.boundingBox();if(box)expect(box.width).toBeGreaterThan(38)}});

  test('admin login, CSV order, reveal and export',async({page})=>{await adminLogin(page);await page.getByRole('button',{name:'用户设置'}).click();const csv=Buffer.from('\ufeff用户名\n顺序甲\n顺序乙\n测试用户\n','utf8');await page.locator('#csv-file').setInputFiles({name:'users.csv',mimeType:'text/csv',buffer:csv});await expect(page.locator('#import-result')).toHaveText(/(?:新增 2 位，更新 1 位|新增 0 位，更新 3 位)，忽略 0 个空行。/);const names=await page.locator('tbody tr td:nth-child(2)').allTextContents();expect(names.indexOf('顺序甲')).toBeLessThan(names.indexOf('顺序乙'));const userRow=page.locator('tbody tr',{hasText:'测试用户'});const passwordValue=userRow.locator('.password-value');await userRow.getByRole('button',{name:'显示'}).click();await expect(passwordValue).not.toHaveText('••••••••••');userPassword=(await passwordValue.textContent())?.trim()||'';expect(userPassword).toHaveLength(10);expect(userPassword).not.toBe(originalUserPassword);const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'导出用户名密码'}).click();expect((await downloadPromise).suggestedFilename()).toContain('PrinterWLAN_Users.csv')});

  test('administrator selects and retains the shared printer',async({page})=>{await adminLogin(page);await page.getByRole('button',{name:'打印机设置'}).click();await expect(page.getByRole('heading',{name:'打印机设置'})).toBeVisible();const printerB=page.locator('.printer-card',{hasText:'PrinterWLAN Test Printer B'});const selectB=printerB.locator('.select-printer');if(await selectB.isEnabled())await selectB.click();await expect(page.locator('.current-printer')).toContainText('PrinterWLAN Test Printer B');await page.reload();await page.getByRole('button',{name:'打印机设置'}).click();await expect(page.locator('.current-printer')).toContainText('PrinterWLAN Test Printer B');const printerA=page.locator('.printer-card',{hasText:'PrinterWLAN Test Printer A'});await printerA.getByRole('button',{name:'设为当前打印机'}).click();await expect(page.locator('.current-printer')).toContainText('PrinterWLAN Test Printer A')});

  test('PDF preview uses administrator capabilities without a printer selector',async({page})=>{await userLogin(page);await page.locator('#file-input').setInputFiles('../../artifacts/smoke/sample.pdf');await expect(page.getByRole('heading',{name:'打印设置'})).toBeVisible({timeout:30000});await expect.poll(()=>page.locator('#pdf-canvas').evaluate(canvas=>canvas.width>0&&canvas.height>0)).toBe(true);await expect(page.locator('#printer')).toHaveCount(0);await expect(page.getByText('打印机由管理员统一设置。')).toBeVisible();await expect(page.getByText('PrinterWLAN Test Printer B')).toHaveCount(0);await page.locator('#copies').fill('21');await page.getByRole('button',{name:'提交打印'}).click();await expect(page.locator('#print-error')).toContainText('最多打印 20 页')});

  test('mobile print view has no printer selector or printer identity',async({page})=>{await page.setViewportSize({width:320,height:800});await userLogin(page);await page.locator('#file-input').setInputFiles('../../artifacts/smoke/sample.pdf');await expect(page.getByRole('heading',{name:'打印设置'})).toBeVisible({timeout:30000});await expect(page.locator('#printer')).toHaveCount(0);await expect(page.getByText(/PrinterWLAN Test Printer/)).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});

  test('usage records and protected clear confirmation',async({page})=>{await adminLogin(page);await expect(page.locator('#records-table tbody tr').first()).toBeVisible();await page.getByRole('button',{name:'清空日志'}).click();await expect(page.getByText('此操作会永久删除全部使用记录和打印记录。')).toBeVisible();await page.locator('#clear-password').fill('wrong');await page.getByRole('button',{name:'永久清空'}).click();await expect(page.locator('#clear-error')).toContainText('不正确');await page.locator('#clear-password').fill(adminPassword);await page.getByRole('button',{name:'永久清空'}).click();await expect(page.getByText('清空全部日志')).not.toBeVisible();});
});
