param(
  [string]$InstallerPath,
  [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts/smoke'),
  [string]$AdminPassword = $env:PRINTERWLAN_ADMIN_PASSWORD
)
$ErrorActionPreference = 'Stop'
if (-not (Test-Path $InstallerPath)) { throw "Installer not found: $InstallerPath" }
if ([string]::IsNullOrWhiteSpace($AdminPassword)) { throw 'PRINTERWLAN_ADMIN_PASSWORD must be generated by the CI job.' }
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null

function New-TestPdf([string]$Path) {
  $objects = @(
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    $null,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'
  )
  $content = 'BT /F1 24 Tf 72 720 Td (PrinterWLAN Smoke Test) Tj ET'
  $objects[3] = "<< /Length $($content.Length) >>`nstream`n$content`nendstream"
  $builder = [System.Text.StringBuilder]::new("%PDF-1.4`n")
  $offsets = [System.Collections.Generic.List[int]]::new()
  for ($i=0; $i -lt $objects.Count; $i++) {
    $offsets.Add([Text.Encoding]::ASCII.GetByteCount($builder.ToString()))
    [void]$builder.Append("$($i+1) 0 obj`n$($objects[$i])`nendobj`n")
  }
  $xref = [Text.Encoding]::ASCII.GetByteCount($builder.ToString())
  [void]$builder.Append("xref`n0 6`n0000000000 65535 f `n")
  foreach ($offset in $offsets) { [void]$builder.Append(('{0:0000000000} 00000 n ' -f $offset)+"`n") }
  [void]$builder.Append("trailer`n<< /Size 6 /Root 1 0 R >>`nstartxref`n$xref`n%%EOF`n")
  [IO.File]::WriteAllText($Path,$builder.ToString(),[Text.Encoding]::ASCII)
}

function New-TestDocx([string]$Path) {
  Add-Type -AssemblyName System.IO.Compression
  if (Test-Path $Path) { Remove-Item $Path -Force }
  $file = [IO.File]::Open($Path,[IO.FileMode]::CreateNew)
  try {
    $zip = [IO.Compression.ZipArchive]::new($file,[IO.Compression.ZipArchiveMode]::Create,$true)
    $entries = @{
      '[Content_Types].xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>'
      '_rels/.rels' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>'
      'word/document.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>PrinterWLAN 中文 Word Smoke Test</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr></w:body></w:document>'
      'docProps/core.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dcterms:created xsi:type="dcterms:W3CDTF">2026-09-15T00:00:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-15T01:00:00Z</dcterms:modified></cp:coreProperties>'
    }
    foreach ($name in $entries.Keys) {
      $entry=$zip.CreateEntry($name);$stream=$entry.Open();$writer=[IO.StreamWriter]::new($stream,[Text.UTF8Encoding]::new($false));
      try {$writer.Write($entries[$name])} finally {$writer.Dispose()}
    }
    $zip.Dispose()
  } finally { $file.Dispose() }
}

function Get-Csrf($Session) { return ($Session.Cookies.GetCookies('http://127.0.0.1:8080') | Where-Object Name -eq 'PrinterWLAN-CSRF').Value }
function Get-Headers($Session) { return @{ 'X-CSRF-Token'=(Get-Csrf $Session); 'X-Device-Id'='00000000-0000-4000-8000-000000000001'; 'X-Session-Id'='smoke-test-session'; 'X-Viewport'='1366x768'; 'X-Screen'='1920x1080'; 'X-Timezone'='UTC' } }

Start-Process $InstallerPath -ArgumentList @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/FAKEPRINTER') -Wait
$deadline=(Get-Date).AddMinutes(2)
do { try { $health=Invoke-RestMethod 'http://127.0.0.1:8080/health' -TimeoutSec 3; break } catch { Start-Sleep -Seconds 2 } } while ((Get-Date) -lt $deadline)
if ($health.status -ne 'ok') { throw 'Health endpoint did not become ready.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" status
if ($LASTEXITCODE -ne 0) { throw 'printerwlan status failed.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" pwd $AdminPassword
if ($LASTEXITCODE -ne 0) { throw 'printerwlan pwd failed.' }

$admin=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $admin | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json' -Body (@{password=$AdminPassword}|ConvertTo-Json) | Out-Null
$csvPath=Join-Path $OutputDirectory 'users.csv'; [IO.File]::WriteAllText($csvPath,"用户名`r`n测试用户`r`n",[Text.UTF8Encoding]::new($true))
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/users/import' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -Form @{file=Get-Item $csvPath} | Out-Null
$exportPath=Join-Path $OutputDirectory 'users-export.csv'
Invoke-WebRequest 'http://127.0.0.1:8080/api/admin/users/export' -WebSession $admin -OutFile $exportPath | Out-Null
$credentials=Import-Csv $exportPath | Where-Object 用户名 -eq '测试用户' | Select-Object -First 1
if (-not $credentials.密码 -or $credentials.密码.Length -ne 10) { throw 'Generated user password was not exportable or was not 10 characters.' }
"PRINTERWLAN_TEST_USER_PASSWORD=$($credentials.密码)" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append

$user=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $user | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json' -Body (@{username='测试用户';password=$credentials.密码}|ConvertTo-Json) | Out-Null
$pdfPath=Join-Path $OutputDirectory 'sample.pdf';New-TestPdf $pdfPath
$upload=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/documents' -Method Post -WebSession $user -Headers (Get-Headers $user) -Form @{file=Get-Item $pdfPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($upload.totalPages -ne 1) { throw 'PDF page count smoke test failed.' }
$printers=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/printers' -WebSession $user
if ($printers.Count -ne 1 -or $printers[0].name -ne 'PrinterWLAN Test Printer') { throw 'Fake printer was not active.' }
$jobRequest=@{documentId=$upload.id;printerName=$printers[0].name;paperSize='A4';orientation='portrait';duplex='simplex';pageRange='all';copies=1;collate=$true;colorMode='color';paperSource='Auto';resolution='0:600:600';scaleMode='fit';scalePercent=100;center=$true}|ConvertTo-Json
$job=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/jobs' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json' -Body $jobRequest
for($i=0;$i -lt 30;$i++){ $status=Invoke-RestMethod "http://127.0.0.1:8080/api/user/jobs/$($job.jobId)" -WebSession $user;if($status.status -eq 'sent'){break};if($status.status -eq 'failed'){throw $status.friendlyError};Start-Sleep -Milliseconds 500 }
if ($status.status -ne 'sent') { throw 'Fake printer job did not reach sent state.' }

$docxPath=Join-Path $OutputDirectory '中文 sample.docx';New-TestDocx $docxPath
$word=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/documents' -Method Post -WebSession $user -Headers (Get-Headers $user) -Form @{file=Get-Item $docxPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($word.totalPages -lt 1) { throw 'Word to PDF conversion smoke test failed.' }
Invoke-RestMethod "http://127.0.0.1:8080/api/user/documents/$($word.id)" -Method Delete -WebSession $user -Headers (Get-Headers $user) | Out-Null
Write-Host 'Installer, service, HTTP, authentication, PDF, Word, and fake print smoke tests passed.'
