param(
  [string]$InstallerPath,
  [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts/smoke'),
  [string]$AdminPassword = $env:PRINTERWLAN_ADMIN_PASSWORD,
  [ValidateSet('Fake','SystemPdf')][string]$PrinterMode = 'Fake'
)
$ErrorActionPreference = 'Stop'
if (-not (Test-Path $InstallerPath)) { throw "Installer not found: $InstallerPath" }
if ([string]::IsNullOrWhiteSpace($AdminPassword)) { throw 'PRINTERWLAN_ADMIN_PASSWORD must be generated by the CI job.' }
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$testPrinterName = 'PrinterWLAN Windows Compatibility Printer'
$printedPdfPath = Join-Path $OutputDirectory 'windows-driver-output.pdf'
$driverOutputDirectory = Join-Path $env:ProgramData 'PrinterWLAN\Diagnostics'
$driverOutputPath = Join-Path $driverOutputDirectory 'windows-driver-output.pdf'

function Install-SystemPdfPrinter {
  New-Item -ItemType Directory -Force $driverOutputDirectory | Out-Null
  if (Test-Path $printedPdfPath) { Remove-Item $printedPdfPath -Force }
  if (Test-Path $driverOutputPath) { Remove-Item $driverOutputPath -Force }
  $feature = Get-WindowsOptionalFeature -Online -FeatureName Printing-PrintToPDFServices-Features -ErrorAction SilentlyContinue
  if ($feature -and $feature.State -ne 'Enabled') {
    Enable-WindowsOptionalFeature -Online -FeatureName Printing-PrintToPDFServices-Features -All -NoRestart | Out-Null
    Restart-Service Spooler -Force
  }
  $driver = Get-PrinterDriver | Where-Object Name -Like '*Print*PDF*' | Select-Object -First 1
  if (-not $driver) { throw 'The Windows Microsoft Print to PDF driver is unavailable.' }
  Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
  Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
  Add-PrinterPort -Name $driverOutputPath
  Add-Printer -Name $testPrinterName -DriverName $driver.Name -PortName $driverOutputPath
}

function Remove-SystemPdfPrinter {
  Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
  Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
}

function New-TestPdf([string]$Path) {
  $source = Join-Path (Split-Path -Parent $Path) 'pdf-source.docx'
  New-TestDocx $source
  $profile = Join-Path (Split-Path -Parent $Path) ('pdf-profile-' + [Guid]::NewGuid().ToString('N'))
  New-Item -ItemType Directory -Force $profile | Out-Null
  $profileUri = ([Uri]($profile + [IO.Path]::DirectorySeparatorChar)).AbsoluteUri
  $soffice = "$env:ProgramFiles\PrinterWLAN\third-party\LibreOffice\program\soffice.com"
  & $soffice "-env:UserInstallation=$profileUri" '--headless' '--nologo' '--nodefault' '--nofirststartwizard' '--norestore' '--convert-to' 'pdf' '--outdir' (Split-Path -Parent $Path) $source | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "Bundled LibreOffice could not generate the PDF smoke fixture (exit $LASTEXITCODE)." }
  $generated = [IO.Path]::ChangeExtension($source, '.pdf')
  if (-not (Test-Path $generated)) { throw 'Bundled LibreOffice did not create the PDF smoke fixture.' }
  Move-Item $generated $Path -Force
}

function New-TestDocx([string]$Path) {
  Add-Type -AssemblyName System.IO.Compression
  if (Test-Path $Path) { Remove-Item $Path -Force }
  $file = [IO.File]::Open($Path,[IO.FileMode]::CreateNew)
  try {
    $zip = [IO.Compression.ZipArchive]::new($file,[IO.Compression.ZipArchiveMode]::Create,$true)
    $entries = @{
      '[Content_Types].xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>'
      '_rels/.rels' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>'
      'word/document.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>PrinterWLAN 中文 Word Smoke Test</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr></w:body></w:document>'
      'docProps/core.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dcterms:created xsi:type="dcterms:W3CDTF">2026-09-15T00:00:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-15T01:00:00Z</dcterms:modified></cp:coreProperties>'
    }
    foreach ($name in $entries.Keys) {
      $entry=$zip.CreateEntry($name);$stream=$entry.Open();$writer=[IO.StreamWriter]::new($stream,[Text.UTF8Encoding]::new($false));
      try {$writer.Write($entries[$name])} finally {$writer.Dispose()}
    }
    $zip.Dispose()
  } finally { $file.Dispose() }
}

function Get-Csrf($Session) { return ($Session.Cookies.GetCookies('http://127.0.0.1:8080') | Where-Object Name -eq 'PrinterWLAN-CSRF').Value }
function Get-Headers($Session) { return @{ 'X-CSRF-Token'=(Get-Csrf $Session); 'X-Device-Id'='00000000-0000-4000-8000-000000000001'; 'X-Session-Id'='smoke-test-session'; 'X-Viewport'='1366x768'; 'X-Screen'='1920x1080'; 'X-Timezone'='UTC' } }

try {
if ($PrinterMode -eq 'SystemPdf') { Install-SystemPdfPrinter }
$installerArguments = @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART')
if ($PrinterMode -eq 'Fake') { $installerArguments += '/FAKEPRINTER' }
Start-Process $InstallerPath -ArgumentList $installerArguments -Wait
$deadline=(Get-Date).AddMinutes(2)
do { try { $health=Invoke-RestMethod 'http://127.0.0.1:8080/health' -TimeoutSec 3; break } catch { Start-Sleep -Seconds 2 } } while ((Get-Date) -lt $deadline)
if ($health.status -ne 'ok') { throw 'Health endpoint did not become ready.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" status
if ($LASTEXITCODE -ne 0) { throw 'printerwlan status failed.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" doctor
if ($LASTEXITCODE -ne 0) { throw 'printerwlan doctor found a compatibility problem.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" pwd $AdminPassword
if ($LASTEXITCODE -ne 0) { throw 'printerwlan pwd failed.' }

$admin=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $admin | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json' -Body (@{password=$AdminPassword}|ConvertTo-Json) | Out-Null
$printerState=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $admin
if ($PrinterMode -eq 'Fake' -and $printerState.printers.Count -ne 2) { throw 'Fake printer inventory was not available to the administrator.' }
$expectedPrinterName = if ($PrinterMode -eq 'Fake') { 'PrinterWLAN Test Printer A' } else { $testPrinterName }
$selectedPrinter=$printerState.printers | Where-Object name -eq $expectedPrinterName | Select-Object -First 1
if (-not $selectedPrinter) { throw "Expected printer was not found: $expectedPrinterName" }
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printer' -Method Put -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json' -Body (@{printerId=$selectedPrinter.id}|ConvertTo-Json) | Out-Null
$persistedPrinter=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $admin
if ($persistedPrinter.selectedPrinterId -ne $selectedPrinter.id) { throw 'Administrator printer selection did not persist.' }
$csvPath=Join-Path $OutputDirectory 'users.csv'; [IO.File]::WriteAllText($csvPath,"用户名`r`n测试用户`r`n",[Text.UTF8Encoding]::new($true))
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/users/import' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -Form @{file=Get-Item $csvPath} | Out-Null
$exportPath=Join-Path $OutputDirectory 'users-export.csv'
Invoke-WebRequest 'http://127.0.0.1:8080/api/admin/users/export' -WebSession $admin -OutFile $exportPath | Out-Null
$credentials=Import-Csv $exportPath | Where-Object 用户名 -eq '测试用户' | Select-Object -First 1
if (-not $credentials.密码 -or $credentials.密码.Length -ne 10) { throw 'Generated user password was not exportable or was not 10 characters.' }
"PRINTERWLAN_TEST_USER_PASSWORD=$($credentials.密码)" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append

$user=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $user | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json' -Body (@{username='测试用户';password=$credentials.密码}|ConvertTo-Json) | Out-Null
$pdfPath=Join-Path $OutputDirectory 'sample.pdf';New-TestPdf $pdfPath
$upload=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/documents' -Method Post -WebSession $user -Headers (Get-Headers $user) -Form @{file=Get-Item $pdfPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($upload.totalPages -ne 1) { throw 'PDF page count smoke test failed.' }
$capabilities=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/print-capabilities' -WebSession $user
if (-not $capabilities.available -or $capabilities.PSObject.Properties.Name -contains 'name' -or $capabilities.PSObject.Properties.Name -contains 'id') { throw 'User capability endpoint exposed an invalid printer state or identity.' }
$paper = $capabilities.paperSizes | Where-Object name -eq 'A4' | Select-Object -First 1
if (-not $paper) { $paper = $capabilities.paperSizes | Select-Object -First 1 }
if (-not $paper) { throw 'Selected printer did not expose a paper size.' }
$source = $capabilities.paperSources | Select-Object -First 1
$resolution = $capabilities.resolutions | Select-Object -First 1
$colorMode = if ($capabilities.supportsColor) { 'color' } else { 'grayscale' }
$sourceName = if ($source) { $source.name } else { $null }
$resolutionKey = if ($resolution) { "$($resolution.rawKind):$($resolution.x):$($resolution.y)" } else { $null }
$jobRequest=@{documentId=$upload.id;paperSize=$paper.name;orientation='portrait';duplex='simplex';pageRange='all';copies=1;collate=$false;colorMode=$colorMode;paperSource=$sourceName;resolution=$resolutionKey;scaleMode='fit';scalePercent=100;center=$true}|ConvertTo-Json
$job=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/jobs' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json' -Body $jobRequest
for($i=0;$i -lt 30;$i++){ $status=Invoke-RestMethod "http://127.0.0.1:8080/api/user/jobs/$($job.jobId)" -WebSession $user;if($status.status -eq 'sent'){break};if($status.status -eq 'failed'){throw $status.friendlyError};Start-Sleep -Milliseconds 500 }
if ($status.status -ne 'sent') { throw "$PrinterMode printer job did not reach sent state." }
if ($PrinterMode -eq 'SystemPdf') {
  $printDeadline=(Get-Date).AddSeconds(60)
  do { if ((Test-Path $driverOutputPath) -and (Get-Item $driverOutputPath).Length -gt 4) { break }; Start-Sleep -Seconds 1 } while ((Get-Date) -lt $printDeadline)
  if (-not (Test-Path $driverOutputPath) -or (Get-Item $driverOutputPath).Length -le 4) {
    Write-Host 'Windows PDF-driver diagnostics:'
    Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue | Format-List Name,DriverName,PortName,PrinterStatus,WorkOffline
    Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Format-List Name,Description,PrinterHostAddress,PortMonitor
    Get-PrintJob -PrinterName $testPrinterName -ErrorAction SilentlyContinue | Format-List ID,DocumentName,JobStatus,SubmittedTime,Size,TotalPages
    throw 'Windows print driver did not create an output file in the service-writable diagnostics directory.'
  }
  $signature=[IO.File]::ReadAllBytes($driverOutputPath)[0..4]
  if ([Text.Encoding]::ASCII.GetString($signature) -ne '%PDF-') { throw 'Windows print driver output is not a PDF.' }
  Copy-Item $driverOutputPath $printedPdfPath -Force
}

$docxPath=Join-Path $OutputDirectory '中文 sample.docx';New-TestDocx $docxPath
$word=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/documents' -Method Post -WebSession $user -Headers (Get-Headers $user) -Form @{file=Get-Item $docxPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($word.totalPages -lt 1) { throw 'Word to PDF conversion smoke test failed.' }
Invoke-RestMethod "http://127.0.0.1:8080/api/user/documents/$($word.id)" -Method Delete -WebSession $user -Headers (Get-Headers $user) | Out-Null
Write-Host "Installer, service, HTTP, authentication, PDF, Word, and $PrinterMode print smoke tests passed."
}
finally {
  if ($PrinterMode -eq 'SystemPdf') { Remove-SystemPdfPrinter }
}
