param(
  [string]$InstallerPath,
  [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts/smoke'),
  [string]$AdminPassword = $env:PRINTERWLAN_ADMIN_PASSWORD,
  [ValidateSet('Fake','SystemPdf')][string]$PrinterMode = 'Fake',
  [bool]$CleanInstall = $true
)
$ErrorActionPreference = 'Stop'
if (-not (Test-Path $InstallerPath)) { throw "Installer not found: $InstallerPath" }
if ([string]::IsNullOrWhiteSpace($AdminPassword)) { throw 'PRINTERWLAN_ADMIN_PASSWORD must be generated by the CI job.' }
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$testPrinterName = 'PrinterWLAN Windows Compatibility Printer'
$nativeTestPrinterName = 'PrinterWLAN Native Driver Control Printer'
$printedPdfPath = Join-Path $OutputDirectory 'windows-driver-output.pdf'
$driverOutputDirectory = Join-Path $env:ProgramData 'PrinterWLAN\Diagnostics'
$driverOutputPath = Join-Path $driverOutputDirectory 'windows-driver-output.pdf'
$nativeDriverOutputPath = Join-Path $driverOutputDirectory 'native-driver-control-output.pdf'

function Install-SystemPdfPrinter {
  New-Item -ItemType Directory -Force $driverOutputDirectory | Out-Null
  if (Test-Path $printedPdfPath) { Remove-Item $printedPdfPath -Force }
  if (Test-Path $driverOutputPath) { Remove-Item $driverOutputPath -Force }
  if (Test-Path $nativeDriverOutputPath) { Remove-Item $nativeDriverOutputPath -Force }
  $feature = Get-WindowsOptionalFeature -Online -FeatureName Printing-PrintToPDFServices-Features -ErrorAction SilentlyContinue
  if ($feature -and $feature.State -ne 'Enabled') {
    Enable-WindowsOptionalFeature -Online -FeatureName Printing-PrintToPDFServices-Features -All -NoRestart | Out-Null
    Restart-Service Spooler -Force
  }
  $driver = Get-PrinterDriver | Where-Object Name -Like '*Print*PDF*' | Select-Object -First 1
  if (-not $driver) { throw 'The Windows Microsoft Print to PDF driver is unavailable.' }
  Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
  Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
  Add-PrinterPort -Name $driverOutputPath
  Add-Printer -Name $testPrinterName -DriverName $driver.Name -PortName $driverOutputPath
}

function Remove-SystemPdfPrinter {
  Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
  Get-Printer -Name $nativeTestPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
  Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
  Get-PrinterPort -Name $nativeDriverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
}

function New-TestPdf([string]$Path) {
  $source = Join-Path (Split-Path -Parent $Path) 'pdf-source.docx'
  New-TestDocx $source
  $profile = Join-Path (Split-Path -Parent $Path) ('pdf-profile-' + [Guid]::NewGuid().ToString('N'))
  New-Item -ItemType Directory -Force $profile | Out-Null
  $profileUri = ([Uri]($profile + [IO.Path]::DirectorySeparatorChar)).AbsoluteUri
  $soffice = "$env:ProgramFiles\PrinterWLAN\third-party\LibreOffice\program\soffice.com"
  & $soffice "-env:UserInstallation=$profileUri" '--headless' '--nologo' '--nodefault' '--nofirststartwizard' '--norestore' '--convert-to' 'pdf' '--outdir' (Split-Path -Parent $Path) $source | Out-Null
  if ($LASTEXITCODE -ne 0) { throw "Bundled LibreOffice could not generate the PDF smoke fixture (exit $LASTEXITCODE)." }
  $generated = [IO.Path]::ChangeExtension($source, '.pdf')
  if (-not (Test-Path $generated)) { throw 'Bundled LibreOffice did not create the PDF smoke fixture.' }
  Move-Item $generated $Path -Force
}

function New-TestDocx([string]$Path) {
  Add-Type -AssemblyName System.IO.Compression
  if (Test-Path $Path) { Remove-Item $Path -Force }
  $file = [IO.File]::Open($Path,[IO.FileMode]::CreateNew)
  try {
    $zip = [IO.Compression.ZipArchive]::new($file,[IO.Compression.ZipArchiveMode]::Create,$true)
    $entries = @{
      '[Content_Types].xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>'
      '_rels/.rels' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>'
      'word/document.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>PrinterWLAN 中文 Word Smoke Test</w:t></w:r></w:p><w:sectPr><w:pgSz w:w="11906" w:h="16838"/></w:sectPr></w:body></w:document>'
      'docProps/core.xml' = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dcterms:created xsi:type="dcterms:W3CDTF">2026-09-15T00:00:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-15T01:00:00Z</dcterms:modified></cp:coreProperties>'
    }
    foreach ($name in $entries.Keys) {
      $entry=$zip.CreateEntry($name);$stream=$entry.Open();$writer=[IO.StreamWriter]::new($stream,[Text.UTF8Encoding]::new($false));
      try {$writer.Write($entries[$name])} finally {$writer.Dispose()}
    }
    $zip.Dispose()
  } finally { $file.Dispose() }
}

function Get-Csrf($Session) { return ($Session.Cookies.GetCookies('http://127.0.0.1:8080') | Where-Object Name -eq 'PrinterWLAN-CSRF').Value }
function Get-Headers($Session) { return @{ 'X-CSRF-Token'=(Get-Csrf $Session); 'X-Device-Id'='00000000-0000-4000-8000-000000000001'; 'X-Session-Id'='smoke-test-session'; 'X-Viewport'='1366x768'; 'X-Screen'='1920x1080'; 'X-Timezone'='UTC' } }
function ConvertTo-Utf8JsonBytes($Value) { return ,[Text.Encoding]::UTF8.GetBytes(($Value | ConvertTo-Json -Compress)) }

function Invoke-MultipartRestMethod {
  param(
    [Parameter(Mandatory=$true)][string]$Uri,
    [Parameter(Mandatory=$true)]$Session,
    [Parameter(Mandatory=$true)][hashtable]$Headers,
    [Parameter(Mandatory=$true)][hashtable]$Form
  )

  $boundary = '----------------PrinterWLAN' + [Guid]::NewGuid().ToString('N')
  $body = [IO.MemoryStream]::new()
  try {
    foreach ($name in $Form.Keys) {
      $value = $Form[$name]
      $prefix = "--$boundary`r`n"
      if ($value -is [IO.FileInfo]) {
        $prefix += "Content-Disposition: form-data; name=`"$name`"; filename=`"$($value.Name)`"`r`n"
        $prefix += "Content-Type: application/octet-stream`r`n`r`n"
        $prefixBytes = [Text.Encoding]::UTF8.GetBytes($prefix)
        $body.Write($prefixBytes, 0, $prefixBytes.Length)
        $file = [IO.File]::OpenRead($value.FullName)
        try { $file.CopyTo($body) } finally { $file.Dispose() }
        $lineBreak = [Text.Encoding]::ASCII.GetBytes("`r`n")
        $body.Write($lineBreak, 0, $lineBreak.Length)
      } else {
        $prefix += "Content-Disposition: form-data; name=`"$name`"`r`n`r`n$value`r`n"
        $prefixBytes = [Text.Encoding]::UTF8.GetBytes($prefix)
        $body.Write($prefixBytes, 0, $prefixBytes.Length)
      }
    }
    $suffix = [Text.Encoding]::ASCII.GetBytes("--$boundary--`r`n")
    $body.Write($suffix, 0, $suffix.Length)

    $request = [Net.HttpWebRequest]::Create($Uri)
    $request.Method = 'POST'
    $request.ContentType = "multipart/form-data; boundary=$boundary"
    $request.ContentLength = $body.Length
    $request.CookieContainer = $Session.Cookies
    foreach ($name in $Headers.Keys) { $request.Headers[$name] = [string]$Headers[$name] }
    $requestStream = $request.GetRequestStream()
    try {
      $body.Position = 0
      $body.CopyTo($requestStream)
    } finally { $requestStream.Dispose() }
    $response = $request.GetResponse()
    try {
      $reader = [IO.StreamReader]::new($response.GetResponseStream(), [Text.Encoding]::UTF8)
      try { return ($reader.ReadToEnd() | ConvertFrom-Json) } finally { $reader.Dispose() }
    } finally { $response.Dispose() }
  } finally { $body.Dispose() }
}

function Invoke-JsonRequestAllowError {
  param(
    [Parameter(Mandatory=$true)][string]$Uri,
    [Parameter(Mandatory=$true)]$Session,
    [Parameter(Mandatory=$true)][hashtable]$Headers,
    [Parameter(Mandatory=$true)][string]$Body
  )

  $parameters = @{
    Uri = $Uri
    Method = 'Post'
    WebSession = $Session
    Headers = $Headers
    ContentType = 'application/json; charset=utf-8'
    Body = [Text.Encoding]::UTF8.GetBytes($Body)
    UseBasicParsing = $true
  }
  if ((Get-Command Invoke-WebRequest).Parameters.ContainsKey('SkipHttpErrorCheck')) {
    return Invoke-WebRequest @parameters -SkipHttpErrorCheck
  }
  try {
    return Invoke-WebRequest @parameters
  } catch {
    $response = $_.Exception.Response
    if (-not $response) { throw }
    $reader = [IO.StreamReader]::new($response.GetResponseStream(), [Text.Encoding]::UTF8)
    try {
      return [pscustomobject]@{
        StatusCode = [int]$response.StatusCode
        Content = $reader.ReadToEnd()
      }
    } finally {
      $reader.Dispose()
      $response.Dispose()
    }
  }
}

try {
if ($CleanInstall) {
  $existingUninstaller = "$env:ProgramFiles\PrinterWLAN\unins000.exe"
  if (Test-Path $existingUninstaller) {
    $cleanup=Start-Process $existingUninstaller -ArgumentList @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/DELETEDATA') -Wait -PassThru
    if ($cleanup.ExitCode -ne 0) { throw "Could not clean the previous smoke-test installation (exit $($cleanup.ExitCode))." }
  }
}
if ($PrinterMode -eq 'SystemPdf') { Install-SystemPdfPrinter }
$installerArguments = @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART')
if ($PrinterMode -eq 'Fake') { $installerArguments += '/FAKEPRINTER' }
Start-Process $InstallerPath -ArgumentList $installerArguments -Wait
$deadline=(Get-Date).AddMinutes(2)
do { try { $health=Invoke-RestMethod 'http://127.0.0.1:8080/health' -TimeoutSec 3; break } catch { Start-Sleep -Seconds 2 } } while ((Get-Date) -lt $deadline)
if ($health.status -ne 'ok') { throw 'Health endpoint did not become ready.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" status
if ($LASTEXITCODE -ne 0) { throw 'printerwlan status failed.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" doctor
if ($LASTEXITCODE -ne 0) { throw 'printerwlan doctor found a compatibility problem.' }
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" pwd $AdminPassword
if ($LASTEXITCODE -ne 0) { throw 'printerwlan pwd failed.' }
& (Join-Path $PSScriptRoot 'ConsoleTest.ps1') -AdminPassword $AdminPassword

$service = Get-CimInstance Win32_Service -Filter "Name='PrinterWLAN'"
if (-not $service -or $service.StartMode -ne 'Auto' -or $service.StartName -ne 'LocalSystem') { throw 'PrinterWLAN service identity or automatic start mode is incorrect.' }
$serviceRegistry = Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\PrinterWLAN'
if ($serviceRegistry.DelayedAutoStart -ne 1 -or @($serviceRegistry.DependOnService) -notcontains 'Spooler') { throw 'PrinterWLAN service is not delayed-auto or does not depend on Spooler.' }
$failurePolicy = (& sc.exe qfailure PrinterWLAN | Out-String)
if ($failurePolicy -notmatch '5000' -or $failurePolicy -notmatch '15000' -or $failurePolicy -notmatch '60000') { throw 'PrinterWLAN service recovery policy is incomplete.' }
$firewallRules = @(Get-NetFirewallRule -DisplayName 'PrinterWLAN HTTP 8080' -ErrorAction SilentlyContinue)
if ($firewallRules.Count -ne 1 -or $firewallRules[0].Enabled -ne 'True') { throw 'PrinterWLAN firewall rule is missing or duplicated.' }
$machinePath = [Environment]::GetEnvironmentVariable('Path','Machine')
if (($machinePath -split ';') -notcontains "$env:ProgramFiles\PrinterWLAN") { throw 'PrinterWLAN install directory is missing from machine PATH.' }
$lanIp = Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notmatch '^(127\.|169\.254\.)' -and $_.InterfaceAlias -notmatch 'Loopback' } | Sort-Object InterfaceMetric | Select-Object -ExpandProperty IPAddress -First 1
if (-not $lanIp) { throw 'No non-loopback IPv4 address is available for the LAN HTTP regression test.' }
$lanBaseUrl = "http://${lanIp}:8080"
if ((Invoke-RestMethod "$lanBaseUrl/health" -TimeoutSec 10).status -ne 'ok') { throw "LAN health check failed at $lanBaseUrl." }
if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_ENV)) {
  "PRINTERWLAN_BASE_URL=$lanBaseUrl" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
  "PRINTERWLAN_REQUIRE_LAN_HTTP=1" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
}
Write-Host "Real non-loopback LAN HTTP target: $lanBaseUrl"

$admin=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $admin | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{password=$AdminPassword}) | Out-Null
$printerState=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $admin
if ($PrinterMode -eq 'Fake' -and $printerState.printers.Count -ne 2) { throw 'Fake printer inventory was not available to the administrator.' }
$csvPath=Join-Path $OutputDirectory 'users.csv'; [IO.File]::WriteAllText($csvPath,"用户名`r`n测试用户`r`n",[Text.UTF8Encoding]::new($true))
Invoke-MultipartRestMethod 'http://127.0.0.1:8080/api/admin/users/import' $admin (Get-Headers $admin) @{file=Get-Item $csvPath} | Out-Null
$exportPath=Join-Path $OutputDirectory 'users-export.csv'
Invoke-WebRequest 'http://127.0.0.1:8080/api/admin/users/export' -WebSession $admin -OutFile $exportPath -UseBasicParsing | Out-Null
$credentials=Import-Csv $exportPath | Where-Object 用户名 -eq '测试用户' | Select-Object -First 1
if (-not $credentials.密码 -or $credentials.密码.Length -ne 10) { throw 'Generated user password was not exportable or was not 10 characters.' }
if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_ENV)) {
  Write-Host "::add-mask::$($credentials.密码)"
  "PRINTERWLAN_TEST_USER_PASSWORD=$($credentials.密码)" | Out-File $env:GITHUB_ENV -Encoding utf8 -Append
}

$user=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $user | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{username='测试用户';password=$credentials.密码}) | Out-Null
$pdfPath=Join-Path $OutputDirectory 'sample.pdf';New-TestPdf $pdfPath
$upload=Invoke-MultipartRestMethod 'http://127.0.0.1:8080/api/user/documents' $user (Get-Headers $user) @{file=Get-Item $pdfPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($upload.totalPages -ne 1) { throw 'PDF page count smoke test failed.' }
$unconfigured=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/print-capabilities' -WebSession $user
if ($unconfigured.configured -or $unconfigured.available) { throw 'A fresh installation unexpectedly selected a printer.' }
$previewResponse=Invoke-WebRequest "http://127.0.0.1:8080/api/user/documents/$($upload.id)/preview" -WebSession $user -UseBasicParsing
if ($previewResponse.StatusCode -ne 200 -or $previewResponse.Headers.'Content-Type' -notmatch 'application/pdf') { throw 'Upload/preview was not available before printer configuration.' }
$blockedJob=Invoke-JsonRequestAllowError 'http://127.0.0.1:8080/api/user/jobs' $user (Get-Headers $user) (@{documentId=$upload.id;paperSize='A4'}|ConvertTo-Json)
if ($blockedJob.StatusCode -ne 400 -or $blockedJob.Content -notmatch '暂未配置打印机') { throw 'Printing was not blocked while no administrator printer was configured.' }

$expectedPrinterName = if ($PrinterMode -eq 'Fake') { 'PrinterWLAN Test Printer A' } else { $testPrinterName }
$selectedPrinter=$printerState.printers | Where-Object name -eq $expectedPrinterName | Select-Object -First 1
if (-not $selectedPrinter) { throw "Expected printer was not found: $expectedPrinterName" }
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printer' -Method Put -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{printerId=$selectedPrinter.id}) | Out-Null
Restart-Service PrinterWLAN -Force
$deadline=(Get-Date).AddMinutes(2)
do { try { $health=Invoke-RestMethod 'http://127.0.0.1:8080/health' -TimeoutSec 3; break } catch { Start-Sleep -Seconds 2 } } while ((Get-Date) -lt $deadline)
if ($health.status -ne 'ok') { throw 'Service did not recover after the printer persistence restart test.' }
$admin=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $admin | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $admin -Headers (Get-Headers $admin) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{password=$AdminPassword}) | Out-Null
$persistedPrinter=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $admin
if ($persistedPrinter.selectedPrinterId -ne $selectedPrinter.id -or $persistedPrinter.selectedPrinterName -ne $selectedPrinter.name) { throw 'Administrator printer selection did not survive a service restart.' }
$user=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $user | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{username='测试用户';password=$credentials.密码}) | Out-Null

$capabilities=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/print-capabilities' -WebSession $user
if (-not $capabilities.available -or $capabilities.PSObject.Properties.Name -contains 'name' -or $capabilities.PSObject.Properties.Name -contains 'id') { throw 'User capability endpoint exposed an invalid printer state or identity.' }
foreach ($field in @('printer','printerId','printerName','targetPrinter')) {
  $injectedBody=@{documentId=$upload.id;paperSize='A4'}
  $injectedBody[$field]='PrinterWLAN Test Printer B'
  $injected=$injectedBody|ConvertTo-Json
  $response=Invoke-JsonRequestAllowError 'http://127.0.0.1:8080/api/user/jobs' $user (Get-Headers $user) $injected
  if ($response.StatusCode -ne 400) { throw "Printer identity injection field '$field' was not rejected." }
}
$paper = $capabilities.paperSizes | Where-Object name -eq 'A4' | Select-Object -First 1
if (-not $paper) { $paper = $capabilities.paperSizes | Select-Object -First 1 }
if (-not $paper) { throw 'Selected printer did not expose a paper size.' }
$source = $capabilities.paperSources | Select-Object -First 1
$resolution = $capabilities.resolutions | Select-Object -First 1
$colorMode = if ($capabilities.supportsColor) { 'color' } else { 'grayscale' }
$sourceName = if ($source) { $source.name } else { $null }
$resolutionKey = if ($resolution) { "$($resolution.rawKind):$($resolution.x):$($resolution.y)" } else { $null }
$jobRequest=@{documentId=$upload.id;paperSize=$paper.name;orientation='portrait';duplex='simplex';pageRange='all';copies=1;collate=$false;colorMode=$colorMode;paperSource=$sourceName;resolution=$resolutionKey;scaleMode='fit';scalePercent=100;center=$true}
$job=Invoke-RestMethod 'http://127.0.0.1:8080/api/user/jobs' -Method Post -WebSession $user -Headers (Get-Headers $user) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes $jobRequest)
for($i=0;$i -lt 30;$i++){ $status=Invoke-RestMethod "http://127.0.0.1:8080/api/user/jobs/$($job.jobId)" -WebSession $user;if($status.status -eq 'sent'){break};if($status.status -eq 'failed'){throw $status.friendlyError};Start-Sleep -Milliseconds 500 }
if ($status.status -ne 'sent') { throw "$PrinterMode printer job did not reach sent state." }
if ($PrinterMode -eq 'SystemPdf') {
  $validationMode = 'end-to-end-service-to-windows-driver'
  $validatedOutputPath = $driverOutputPath
  $printDeadline=(Get-Date).AddSeconds(60)
  do { if ((Test-Path $driverOutputPath) -and (Get-Item $driverOutputPath).Length -gt 4) { break }; Start-Sleep -Seconds 1 } while ((Get-Date) -lt $printDeadline)
  if (-not (Test-Path $driverOutputPath) -or (Get-Item $driverOutputPath).Length -le 4) {
    $printer = Get-Printer -Name $testPrinterName -ErrorAction SilentlyContinue
    $spoolJob = Get-PrintJob -PrinterName $testPrinterName -ErrorAction SilentlyContinue | Sort-Object SubmittedTime -Descending | Select-Object -First 1
    Write-Host 'Windows PDF-driver diagnostics:'
    $printer | Format-List Name,DriverName,PortName,PrinterStatus,WorkOffline
    Get-PrinterPort -Name $driverOutputPath -ErrorAction SilentlyContinue | Format-List Name,Description,PrinterHostAddress,PortMonitor
    $spoolJob | Format-List ID,DocumentName,JobStatus,SubmittedTime,Size,TotalPages
    if (-not $spoolJob -or $spoolJob.Size -le 0 -or $spoolJob.TotalPages -lt 1) {
      throw 'PrinterWLAN did not submit a non-empty page to the Windows print spooler.'
    }

    $validationMode = 'spooler-submission-plus-native-driver-control'
    [ordered]@{
      printerWlanJobId = $job.jobId
      processArchitecture = "$([Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture)"
      documentName = $spoolJob.DocumentName
      jobStatus = "$($spoolJob.JobStatus)"
      size = $spoolJob.Size
      totalPages = $spoolJob.TotalPages
      submittedTime = $spoolJob.SubmittedTime
    } | ConvertTo-Json | Set-Content (Join-Path $OutputDirectory 'printerwlan-spooler-evidence.json') -Encoding utf8

    $driverName = $printer.DriverName
    Get-Printer -Name $nativeTestPrinterName -ErrorAction SilentlyContinue | Remove-Printer -ErrorAction SilentlyContinue
    Get-PrinterPort -Name $nativeDriverOutputPath -ErrorAction SilentlyContinue | Remove-PrinterPort -ErrorAction SilentlyContinue
    if (Test-Path $nativeDriverOutputPath) { Remove-Item $nativeDriverOutputPath -Force }
    Add-PrinterPort -Name $nativeDriverOutputPath
    Add-Printer -Name $nativeTestPrinterName -DriverName $driverName -PortName $nativeDriverOutputPath
    $nativeWindowsPowerShell = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
    & $nativeWindowsPowerShell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot 'NativePrintProbe.ps1') -PrinterName $nativeTestPrinterName
    if ($LASTEXITCODE -ne 0) { throw 'The native Windows print-driver control process failed.' }
    $nativeDeadline=(Get-Date).AddSeconds(60)
    do { if ((Test-Path $nativeDriverOutputPath) -and (Get-Item $nativeDriverOutputPath).Length -gt 4) { break }; Start-Sleep -Seconds 1 } while ((Get-Date) -lt $nativeDeadline)
    if (-not (Test-Path $nativeDriverOutputPath) -or (Get-Item $nativeDriverOutputPath).Length -le 4) {
      throw 'The native Windows print-driver control did not create an output file.'
    }
    $validatedOutputPath = $nativeDriverOutputPath
  }
  $signature=[IO.File]::ReadAllBytes($validatedOutputPath)[0..4]
  if ([Text.Encoding]::ASCII.GetString($signature) -ne '%PDF-') { throw 'Windows print driver output is not a PDF.' }
  Copy-Item $validatedOutputPath $printedPdfPath -Force
  [ordered]@{
    mode = $validationMode
    output = $printedPdfPath
    outputBytes = (Get-Item $printedPdfPath).Length
    signature = '%PDF-'
  } | ConvertTo-Json | Set-Content (Join-Path $OutputDirectory 'print-path-evidence.json') -Encoding utf8
}

$docxPath=Join-Path $OutputDirectory '中文 sample.docx';New-TestDocx $docxPath
$word=Invoke-MultipartRestMethod 'http://127.0.0.1:8080/api/user/documents' $user (Get-Headers $user) @{file=Get-Item $docxPath;clientLastModified='2026-09-15T00:00:00Z'}
if ($word.totalPages -lt 1) { throw 'Word to PDF conversion smoke test failed.' }
Invoke-RestMethod "http://127.0.0.1:8080/api/user/documents/$($word.id)" -Method Delete -WebSession $user -Headers (Get-Headers $user) | Out-Null
$tempFiles=@(Get-ChildItem 'C:\ProgramData\PrinterWLAN\Temp' -File -Recurse -ErrorAction SilentlyContinue)
if ($tempFiles.Count -ne 0) { throw "Temporary document cleanup left $($tempFiles.Count) file(s)." }
Write-Host "Installer, service, LAN HTTP, authentication, printer policy, PDF, Word, temporary cleanup, and $PrinterMode print smoke tests passed."
}
finally {
  if ($PrinterMode -eq 'SystemPdf') { Remove-SystemPdfPrinter }
}
