param(
  [string]$CurrentInstallerPath,
  [string]$OutputDirectory = (Join-Path (Split-Path -Parent $PSScriptRoot) 'artifacts/upgrade'),
  [string]$AdminPassword = $env:PRINTERWLAN_ADMIN_PASSWORD,
  [string]$PreviousVersion = '1.2.0',
  [string]$ExpectedVersion = '1.3.0'
)
$ErrorActionPreference = 'Stop'

function Invoke-MultipartRestMethod {
  param(
    [Parameter(Mandatory=$true)][string]$Uri,
    [Parameter(Mandatory=$true)]$Session,
    [Parameter(Mandatory=$true)][hashtable]$Headers,
    [Parameter(Mandatory=$true)][hashtable]$Form
  )

  Add-Type -AssemblyName System.Net.Http
  $handler = [Net.Http.HttpClientHandler]::new()
  $handler.CookieContainer = $Session.Cookies
  $client = [Net.Http.HttpClient]::new($handler)
  $content = [Net.Http.MultipartFormDataContent]::new()
  try {
    foreach ($name in $Headers.Keys) {
      if (-not $client.DefaultRequestHeaders.TryAddWithoutValidation($name, [string]$Headers[$name])) {
        throw "Could not add HTTP test header '$name'."
      }
    }
    foreach ($name in $Form.Keys) {
      $value = $Form[$name]
      if ($value -is [IO.FileInfo]) {
        $fileContent = [Net.Http.ByteArrayContent]::new([IO.File]::ReadAllBytes($value.FullName))
        $fileContent.Headers.ContentType = [Net.Http.Headers.MediaTypeHeaderValue]::new('application/octet-stream')
        $content.Add($fileContent, $name, $value.Name)
      } else {
        $content.Add([Net.Http.StringContent]::new([string]$value, [Text.Encoding]::UTF8), $name)
      }
    }
    $response = $client.PostAsync($Uri, $content).GetAwaiter().GetResult()
    $payload = $response.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    if (-not $response.IsSuccessStatusCode) { throw "Multipart request failed with HTTP $([int]$response.StatusCode): $payload" }
    return $payload | ConvertFrom-Json
  } finally {
    $content.Dispose()
    $client.Dispose()
    $handler.Dispose()
  }
}
if (-not (Test-Path $CurrentInstallerPath)) { throw "Installer not found: $CurrentInstallerPath" }
if ([string]::IsNullOrWhiteSpace($AdminPassword)) { throw 'PRINTERWLAN_ADMIN_PASSWORD must be generated by the CI job.' }
New-Item -ItemType Directory -Force $OutputDirectory | Out-Null

function Wait-ForHealth {
  $deadline=(Get-Date).AddMinutes(2)
  do {
    try { if ((Invoke-RestMethod 'http://127.0.0.1:8080/health' -TimeoutSec 3).status -eq 'ok') { return } }
    catch { Start-Sleep -Seconds 2 }
  } while ((Get-Date) -lt $deadline)
  throw 'PrinterWLAN health endpoint did not become ready.'
}

function Get-Csrf($Session) { return ($Session.Cookies.GetCookies('http://127.0.0.1:8080') | Where-Object Name -eq 'PrinterWLAN-CSRF').Value }
function Get-Headers($Session) { return @{ 'X-CSRF-Token'=(Get-Csrf $Session); 'X-Device-Id'='00000000-0000-4000-8000-000000000002'; 'X-Session-Id'='upgrade-test-session' } }
function ConvertTo-Utf8JsonBytes($Value) { return ,[Text.Encoding]::UTF8.GetBytes(($Value | ConvertTo-Json -Compress)) }

$previousTag="v$PreviousVersion"
$releaseBase="https://github.com/QiaoxiuLi/PrinterWLAN/releases/download/$previousTag"
$oldInstaller=Join-Path $OutputDirectory "PrinterWLAN-$previousTag-Setup-x64.exe"
Invoke-WebRequest "$releaseBase/PrinterWLAN-Setup-x64.exe" -OutFile $oldInstaller
$oldChecksum=Join-Path $OutputDirectory "PrinterWLAN-$previousTag-Setup-x64.exe.sha256"
Invoke-WebRequest "$releaseBase/PrinterWLAN-Setup-x64.exe.sha256" -OutFile $oldChecksum
$expectedHash=((Get-Content $oldChecksum -Raw).Trim() -split '\s+')[0].ToLowerInvariant()
$actualHash=(Get-FileHash $oldInstaller -Algorithm SHA256).Hash.ToLowerInvariant()
if ($actualHash -ne $expectedHash) { throw "Downloaded $previousTag installer did not match its published SHA-256." }
Start-Process $oldInstaller -ArgumentList @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/FAKEPRINTER') -Wait
Wait-ForHealth
& "$env:ProgramFiles\PrinterWLAN\PrinterWLAN.exe" pwd $AdminPassword
if ($LASTEXITCODE -ne 0) { throw "$previousTag administrator password setup failed." }

$before=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $before | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $before -Headers (Get-Headers $before) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{password=$AdminPassword}) | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/settings' -Method Put -WebSession $before -Headers (Get-Headers $before) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{siteName='PrinterWLAN Upgrade Preserved'}) | Out-Null
$csvPath=Join-Path $OutputDirectory 'upgrade-users.csv'
[IO.File]::WriteAllText($csvPath,"用户名`r`n升级保留用户`r`n",[Text.UTF8Encoding]::new($true))
Invoke-MultipartRestMethod 'http://127.0.0.1:8080/api/admin/users/import' $before (Get-Headers $before) @{file=Get-Item $csvPath} | Out-Null
$beforeExport=Join-Path $OutputDirectory "$previousTag-users.csv"
Invoke-WebRequest 'http://127.0.0.1:8080/api/admin/users/export' -WebSession $before -OutFile $beforeExport | Out-Null
$beforeCredential=Import-Csv $beforeExport | Where-Object 用户名 -eq '升级保留用户' | Select-Object -First 1
if (-not $beforeCredential.密码) { throw "$previousTag user credential could not be exported." }
$userBefore=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $userBefore | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $userBefore -Headers (Get-Headers $userBefore) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{username='升级保留用户';password=$beforeCredential.密码}) | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/events' -Method Post -WebSession $userBefore -Headers (Get-Headers $userBefore) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{type='page_view';page='upgrade-preservation'}) | Out-Null
$recordsBefore=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/records?page=1&pageSize=50' -WebSession $before
if ($recordsBefore.total -lt 1) { throw "$previousTag activity data was not created." }
$diagnosticMarker='C:\ProgramData\PrinterWLAN\Diagnostics\upgrade-preservation.txt'
[IO.File]::WriteAllText($diagnosticMarker,'preserve diagnostics',[Text.UTF8Encoding]::new($false))
$beforePrinters=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $before
$selectedPrinter=$beforePrinters.printers | Where-Object name -eq 'PrinterWLAN Test Printer A' | Select-Object -First 1
if (-not $selectedPrinter) { throw "$previousTag fake printer was unavailable." }
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printer' -Method Put -WebSession $before -Headers (Get-Headers $before) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{printerId=$selectedPrinter.id}) | Out-Null

$upgradeProcess=Start-Process $CurrentInstallerPath -ArgumentList @('/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART','/FAKEPRINTER') -Wait -PassThru
if ($upgradeProcess.ExitCode -ne 0) { throw "v$ExpectedVersion in-place installer failed with exit code $($upgradeProcess.ExitCode)." }
if (-not (Get-Service PrinterWLAN -ErrorAction SilentlyContinue)) { throw 'PrinterWLAN service disappeared during the in-place upgrade.' }
Wait-ForHealth
$after=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
$bootstrap=Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $after
if ($bootstrap.siteName -ne 'PrinterWLAN Upgrade Preserved' -or $bootstrap.version -ne $ExpectedVersion) { throw "Upgrade did not preserve the site name or install v$ExpectedVersion." }
Invoke-RestMethod 'http://127.0.0.1:8080/api/admin-login' -Method Post -WebSession $after -Headers (Get-Headers $after) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{password=$AdminPassword}) | Out-Null
$users=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/users?query=%E5%8D%87%E7%BA%A7%E4%BF%9D%E7%95%99%E7%94%A8%E6%88%B7&page=1&pageSize=50' -WebSession $after
if ($users.total -ne 1) { throw 'Upgrade did not preserve the existing user.' }
$afterExport=Join-Path $OutputDirectory "v$ExpectedVersion-users.csv"
Invoke-WebRequest 'http://127.0.0.1:8080/api/admin/users/export' -WebSession $after -OutFile $afterExport | Out-Null
$afterCredential=Import-Csv $afterExport | Where-Object 用户名 -eq '升级保留用户' | Select-Object -First 1
if ($afterCredential.密码 -ne $beforeCredential.密码) { throw 'Upgrade changed the existing user password data.' }
$userAfter=[Microsoft.PowerShell.Commands.WebRequestSession]::new()
Invoke-RestMethod 'http://127.0.0.1:8080/api/bootstrap' -WebSession $userAfter | Out-Null
Invoke-RestMethod 'http://127.0.0.1:8080/api/user-login' -Method Post -WebSession $userAfter -Headers (Get-Headers $userAfter) -ContentType 'application/json; charset=utf-8' -Body (ConvertTo-Utf8JsonBytes @{username='升级保留用户';password=$beforeCredential.密码}) | Out-Null
$recordsAfter=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/records?page=1&pageSize=100' -WebSession $after
if ($recordsAfter.total -lt $recordsBefore.total -or -not ($recordsAfter.items | Where-Object type -eq 'page_view')) { throw 'Upgrade did not preserve Activity database records.' }
if (-not (Test-Path $diagnosticMarker) -or (Get-Content $diagnosticMarker -Raw) -ne 'preserve diagnostics') { throw 'Upgrade did not preserve Diagnostics data.' }
$printers=Invoke-RestMethod 'http://127.0.0.1:8080/api/admin/printers' -WebSession $after
if ($printers.selectedPrinterId -ne $selectedPrinter.id -or $printers.selectedPrinterName -ne $selectedPrinter.name) { throw 'Upgrade did not preserve the administrator printer selection.' }
Write-Host "$previousTag to v$ExpectedVersion in-place upgrade preserved the site, administrator password, users, user password data, printer selection, Activity records, Diagnostics, and service identity."
